name: Build and Publish
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      reference:
        description: 'Reference to the commit or tag to build'
        required: true
        default: 'refs/heads/main'

jobs:
  call-workflow:
    uses: kin/actions/.github/workflows/build-gem.yml@main
