name: Lint and test Rails

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Gems
        run: |
          bundle config set --local rubygems.pkg.github.com kinrobot:${{ secrets.KINROBOT_PACKAGES_READ_PAT }}
          bundle install --jobs 4 --retry 3 --without production

      - name: Lint
        run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    needs: lint
    name: Test
    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: auto_test
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Gems
        run: |
          bundle config set --local rubygems.pkg.github.com kinrobot:${{ secrets.KINROBOT_PACKAGES_READ_PAT }}
          bundle install --jobs 4 --retry 3 --without production

      - name: Bundle
        run: bundle install

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare --trace
          bundle exec rspec --tag ~contract
