name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Lint Ruby
        run: |
          gem install bundler
          bundle config set --global rubygems.pkg.github.com kinrobot:${{ secrets.KINROBOT_PACKAGES_READ_PAT }}
          bundle install
          bundle exec standardrb -D --parallel --display-only-failed --format progress --format junit --out standardrb.xml

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: RSpec Report
        uses: EnricoMi/publish-unit-test-result-action@v2.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: tmp/junit/*.xml
